POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "PDiddy",
    "number": "6767"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "PDiddy"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "6767"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    
}