POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Eric Williams",
    "number": "6767"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Eric Williams"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "6767"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    
}